### ISSUE TITLE
no package.json

### ISSUE THREAD

**Issue by wzapk** [ghanshyamtank59/laravel5Angular4#1]
npm WARN saveError ENOENT: no such file or directory, open 'D:\development\larav
el5Angular4\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'D:\development\laravel5
Angular4\package.json'
npm WARN laravel5Angular4 No description
npm WARN laravel5Angular4 No repository field.
npm WARN laravel5Angular4 No README data
npm WARN laravel5Angular4 No license field.

**Comment by tomek550** [comment]
Same error here, please commit package.json file.

**Comment by KAMAELUA** [comment]
Same...

**Comment by ghanshyamtank59** [comment]
Hello All,
I have added package.json. Please check it.
