### ISSUE TITLE
PHP parse error

### ISSUE THREAD

**Issue by dwaard** [ghanshyamtank59/laravel5Angular4#3]
Following your instructions leads to "PHP Parse error:  syntax error, unexpected 'namespace' (T_NAMESPACE) in C:\My_Code\laravel5Angular4\routes\web.php on line 19"

My PHP version: 5.6.30

**Comment by ghanshyamtank59** [comment]
Laravel 5.4 is supporting php version 5.6.4 or greater.

**Comment by dwaard** [comment]
Thanks for your answer. But, I assumed that 5.6.30 (released jan/2017) is greater than 5.6.4 (released dec/2014). Is that not correct?

**Comment by ghanshyamtank59** [comment]
Yes, So try with enable require modules. Because Laravel 5.4 need to enable below Extensions.

OpenSSL PHP Extension
PDO PHP Extension
Mbstring PHP Extension
Tokenizer PHP Extension
XML PHP Extension

If this will be fixed from your end so make it close.
