### ISSUE TITLE
How to pass data from Laravel to Angular

### ISSUE THREAD

**Issue by Afarooq143** [ghanshyamtank59/laravel5Angular4#4]
Hi @ghanshyamtank59  thanks alot for the this stunning starter the best i been through so far, 
I don't have any issue and its runing awesome screen shot attached.
![lang](https://user-images.githubusercontent.com/16359312/38454649-acaa2108-3a88-11e8-8fb3-c97b81fb30b6.PNG)

Now, can you please ad example how to pass data between laravel & angular (e.g passing some data from laravel to dashboard template & vice versa).
At least i wish "dashboard works" come from back-end (laravel) to  front-end(angular). hope you got me
I'm newbie for this thanks a lot for this starter. Please help out.

**Comment by ghanshyamtank59** [comment]
Hi @Afarooq143,
I have add example of pass data between laravel to angular. I hope it will helpful to you.
Thanks,
